export const lyricsMusic = [
  { time: "00:20.11", text: "Amor, vamos falar sobre o amor" },
  { time: "00:24.37", text: "É tudo aquilo que você esperava?" },
  { time: "00:29.16", text: "Ou o sentimento te assombra?" },
  { time: "00:33.87", text: "Eu sei que esse sentimento te assombra" },
  { time: "00:39.11", text: "Talvez essa seja a noite em que meus sonhos me revelem algo" },
  { time: "00:41.61", text: "Todas as estrelas estão mais próximas" },
  { time: "00:49.11", text: "Talvez essa seja a noite em que meus sonhos me revelem algo" },
  { time: "00:52.13", text: "Todas as estrelas estão mais próximas" },

  { time: "00:59.41", text: "Me diga o que você vai fazer comigo" },
  { time: "01:01.16", text: "Confronto não é novidade pra mim" },
  { time: "01:03.87", text: "Pode me trazer bala, espada, morte" },
  { time: "01:05.61", text: "Mas não consegue me trazer a verdade" },
  { time: "01:07.36", text: "Foda-se você e suas expectativas" },
  { time: "01:11.11", text: "Nem quero seus parabéns" },
  { time: "01:13.62", text: "Reconheço confiança falsa" },
  { time: "01:18.88", text: "Odeio quem se acha no direito" },
  { time: "01:20.87", text: "Me olha torto só porque eu não te convidei" },
  { time: "01:23.61", text: "Ah, você é importante?" },
  { time: "01:24.38", text: "Você é a moral da história? Você que patrocina tudo?" },
  { time: "01:26.13", text: "Filho da p*, eu nem gosto de você" },
  { time: "01:28.62", text: "Corrompa o coração de um homem com um presente" },
  { time: "01:30.88", text: "É assim que você descobre com quem está lidando" },
  { time: "01:33.41", text: "Poucos são com quem construo algo de verdade" },
  { time: "01:35.87", text: "Quero o crédito, ganhando ou perdendo" },
  { time: "01:38.61", text: "Juro pela minha mãe, isso é o mais real que posso ser" },

  { time: "01:39.62", text: "Amor, vamos falar sobre o amor" },
  { time: "01:43.63", text: "É tudo aquilo que você esperava?" },
  { time: "01:48.11", text: "Ou o sentimento te assombra?" },
  { time: "01:50.62", text: "Eu sei que esse sentimento te assombra" },
  { time: "01:58.36", text: "Talvez essa seja a noite em que meus sonhos me revelem algo" },
  { time: "02:01.62", text: "Todas as estrelas estão mais próximas" },
  { time: "02:08.36", text: "Talvez essa seja a noite em que meus sonhos me revelem algo" },
  { time: "02:11.36", text: "Todas as estrelas estão mais próximas" },

  { time: "02:19.37", text: "Pele coberta de ego" },
  { time: "02:21.54", text: "Você começa a falar e eu me envolvo, tipo um rebote" },
  { time: "02:25.74", text: "Sem controle, sem botão de desligar" },
  { time: "02:28.26", text: "É o jeito que você afeta" },
  { time: "02:30.78", text: "É excitante, mas afaste isso de mim" },
  { time: "02:33.03", text: "Saiba que você se enganou" },
  { time: "02:34.60", text: "Fique longe de mim" },
  { time: "02:35.83", text: "Tudo está errado, então tire isso de mim" },
  { time: "02:40.03", text: "Eu só choro sem motivo" },
  { time: "02:42.27", text: "Só oro sem motivo" },
  { time: "02:45.07", text: "Só agradeço pela vida, pelo dia, pelas horas" },
  { time: "02:47.58", text: "E por mais um dia respirando" },
  { time: "02:49.82", text: "Fiz tudo porque me senti bem" },
  { time: "02:52.00", text: "Você poderia viver tudo se se sentisse mal" },
  { time: "02:55.10", text: "Melhor viver sua vida" },
  { time: "02:56.83", text: "Estamos ficando sem tempo" },

  { time: "03:00.70", text: "Amor, vamos falar sobre o amor" },
  { time: "03:02.88", text: "É tudo aquilo que você esperava?" },
  { time: "03:07.62", text: "Ou o sentimento te assombra?" },
  { time: "03:10.12", text: "Eu sei que esse sentimento te assombra" },
  { time: "03:17.65", text: "Talvez essa seja a noite em que meus sonhos me revelem algo" },
  { time: "03:20.89", text: "Todas as estrelas estão mais próximas" },
  { time: "03:27.61", text: "Talvez essa seja a noite em que meus sonhos me revelem algo" },
  { time: "03:30.61", text: "Todas as estrelas estão mais próximas" }
]
