export const lyricsMusic = [
  { time: "00:10.99", text: "O jeito que você escreve" },
  { time: "00:14.13", text: "Meu Deus, sua caligrafia" },
  { time: "00:17.19", text: "O que você faz depois da biblioteca hoje?" },
  { time: "00:23.38", text: "Eu vim só para comprar um papel de carta" },
  { time: "00:29.53", text: "Mas no meu coração já é Jane Austen, \n oh ****" },

  { time: "00:35.80", text: "Em segredo, em segredo, quero te olhar" },
  { time: "00:38.90", text: "Entre as brechas, quero te seguir" },
  { time: "00:42.15", text: "Eu sou o papel, você é a minha caneta" },
  { time: "00:45.21", text: "Será que pode me abrir uma vez?" },
  { time: "00:48.95", text: "Vai me molhar?" },
  { time: "00:51.95", text: "Vai me riscar?" },
  { time: "00:55.04", text: "Vai me entregar? Vai me ler?" },
  { time: "00:57.90", text: "Vai usar seu marcador em mim?" },
  { time: "01:01.35", text: "Não me devolva e nem me perca" },
  { time: "01:04.22", text: "Vai me levar?" },
  { time: "01:07.25", text: "Vai me sublinhar?" },
  { time: "01:08.75", text: "Vai me juntar? Vai me ligar a você?" },

  { time: "01:13.20", text: "O jeito que você lê" },
  { time: "01:15.59", text: "Meu Deus, esses cortes de papel" },
  { time: "01:18.81", text: "O que você vai fazer hoje à noite na biblioteca?" },
  { time: "01:24.88", text: "Nós já tivemos um encontro perfeito uma vez" },
  { time: "01:31.06", text: "Mas no meu coração já somos Scott e Zelda, oh loucura" },
  { time: "01:37.59", text: "Em segredo, em segredo, quero te olhar" },
  { time: "01:40.55", text: "Entre as brechas, quero te seguir" },
  { time: "01:43.61", text: "Eu sou o papel, você é a minha caneta" },
  { time: "01:46.77", text: "Quer me abrir uma vez?" },
  { time: "01:50.46", text: "Vai me molhar? Vai me riscar?" },
  { time: "01:56.67", text: "Vai me entregar? Vai me ler?" },
  { time: "01:59.48", text: "Vai dobrar a página pra marcar?" },
  { time: "02:02.87", text: "Não perca o marcador de página" },
  { time: "02:05.84", text: "Vai me levar? Vai me bater com força?" },
  { time: "02:10.17", text: "Vai me juntar? Vai me lembrar?" },
  { time: "02:14.23", text: "" }
];